inherit_mode:
  merge:
    - Exclude
    
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'lib/flow/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'